//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        public int Id { get; set; }
        public int Balance { get; set; }
        public string NoCuenta { get; set; }
        public string PIN { get; set; }
        public string IdUser { get; set; }
    }
}
